baseURL = "https://www.sisu.io"
languageCode = "en-us"
title = "sisu.io"
theme = "bare"
enableGitInfo = true

[taxonomies]
  tag = "tags"
  series = "series"

[params]
mainSections = ["posts", "openbsd", "neo4j", "presentations"]
hardcodedTags = ["openbsd", "about", "archives"]
author = "Dave Voutila"
email = "dave@sisu.io"
repoLink = "https://github.com/voutilad/sisu.io"
description = "...so it goes."
postcss = false
includeAuthorInTitle = true

[[params.social]]
icon = "twitter-circle"
url = "https://twitter.com/voutilad"

[[params.social]]
icon = "github-circle"
url = "https://github.com/voutilad"

[[params.social]]
icon = "linkedin"
url = "https://linkedin.com/in/dave.voutila"